allow-lan: 'true'
external-controller: :9090
log-level: info
mode: Rule
port: '7890'
proxies:
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš
  password: Sn5B7jTqr76aCJT8
  port: '9097'
  server: 185.167.116.253
  type: ss
- alterId: '64'
  cipher: auto
  name: _CN_ä¸­å›½
  port: '50002'
  server: 112.132.215.189
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½
  network: ws
  port: '8880'
  server: cf-lt.sharecentre.online
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: e59bd762-dacd-445c-8e2a-e1c5812949cb
  ws-opts:
    headers:
      Host: ssrsub.v10.asuka.buzz
    path: /api/v3/download.getFile
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 2
  network: ws
  port: '443'
  server: 172.67.135.55
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7
  ws-opts:
    headers:
      Host: oplg1.cfcdn2.xyz
    path: /AUIKN8AU
- cipher: aes-256-cfb
  name: ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡
  password: amazonskr05
  port: '443'
  server: 13.215.189.221
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 2
  password: f8npKgNzdkss2ytn
  port: '9088'
  server: 185.167.116.253
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬
  password: doub.io
  port: '8080'
  server: 43.207.160.88
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 3
  password: rNBfNuuANFCAk7KB
  port: '9056'
  server: 185.167.116.38
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 2
  obfs: plain
  obfs-param: ''
  password: vyunme
  port: '443'
  protocol: auth_aes128_sha1
  protocol-param: ''
  server: 13.215.27.80
  type: ssr
- cipher: aes-256-cfb
  name: ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 3
  password: amazonskr05
  port: '443'
  server: 54.169.113.143
  type: ss
- name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 3
  password: 4134219f-2384-449c-92e9-50fe8474c30a
  port: '10086'
  server: sanjose-d2.4422331.xyz
  skip-cert-verify: 'false'
  sni: https://mofa.4422331.xyz
  type: trojan
- cipher: aes-256-gcm
  name: ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  password: '114514'
  port: '30042'
  server: out.jijifun.com
  type: ss
- name: ğŸ‡©ğŸ‡ª _DE_å¾·å›½
  password: 5c0eb7b7-6db9-4ff0-a324-62caa9198930
  port: '443'
  server: 84.252.121.218
  skip-cert-verify: 'false'
  sni: vzwzasc.cn
  type: trojan
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 4
  network: ws
  port: '443'
  server: america1.yj2022.ga
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 4b5e4565-322f-4223-a891-78a84f189726
  ws-opts:
    headers:
      Host: america1.yj2022.ga
    path: /
- cipher: aes-256-gcm
  name: ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾
  password: '114514'
  port: '30032'
  server: out.jijifun.com
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡»ğŸ‡³ _VN_è¶Šå—
  network: ws
  port: '80'
  server: 103.143.209.42
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: ee76cecf-1219-42be-ae3f-6b8077e4cacc
  ws-opts:
    path: /
- alterId: '0'
  cipher: auto
  name: _BZ_ä¼¯åˆ©å…¹
  network: ws
  port: '443'
  server: 203.30.191.2
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7
  ws-opts:
    headers:
      Host: oplg1.cfcdn2.xyz
    path: /AUIKN8AU
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 4
  password: UWZQeLRWnkqgkseq
  port: '9032'
  server: 185.167.116.38
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 5
  password: FAdUvMJUq5vDgKEq
  port: '9006'
  server: 185.167.116.38
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 2
  password: amazonskr05
  port: '443'
  server: 43.207.66.114
  type: ss
- alterId: '0'
  cipher: auto
  name: _CN_ä¸­å›½ 2
  port: '31372'
  server: 106.55.234.95
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 6
  password: NvS8N4Vf8qAGPSCL
  port: '9046'
  server: 185.167.116.38
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 5
  network: ws
  port: '443'
  server: vc-usa.181227.xyz
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 2ddcf12d-52fa-4e09-b4f1-c52d5cbee69b
  ws-opts:
    headers:
      Host: vc-usa.181227.xyz
    path: /
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 6
  network: ws
  port: '443'
  server: new3.hucloud-dns.xyz
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: d8eb886b-05be-4628-f2a2-a7e5b305e35a
  ws-opts:
    headers:
      Host: new3.hucloud-dns.xyz
    path: /
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 7
  network: ws
  port: '443'
  server: 172.67.147.152
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 9e6ceeff-2546-3690-ac00-6fcdf31dec94
  ws-opts:
    headers:
      Host: v2fly.samrta.website
    path: /chcara
- cipher: aes-256-cfb
  name: ğŸ‡°ğŸ‡· _KR_éŸ©å›½
  password: amazonskr05
  port: '443'
  server: 43.201.48.212
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡¸ğŸ‡¬ _CN_ä¸­å›½->ğŸ‡¸ğŸ‡¬_SG_æ–°åŠ å¡
  network: ws
  port: '11410'
  server: hy.guanguan.club
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 5707bceb-1da9-41e1-bd03-1bb3d1c28a2c
  ws-opts:
    headers:
      Host: sg1.oraclec.pp.ua
    path: /nba
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 7
  password: HSZuyJQcWe8dxNdF
  port: '9043'
  server: 185.167.116.38
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 8
  password: rNBfNuuANFCAk7KB
  port: '9056'
  server: 185.167.116.253
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 2
  password: amazonskr05
  port: '443'
  server: 43.201.37.176
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 3
  password: amazonskr05
  port: '443'
  server: 43.201.70.114
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 8
  network: ws
  port: '443'
  server: cf-lt.sharecentre.online
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 823c31da-701f-483d-b36e-896e5cf0987a
  ws-opts:
    headers:
      Host: kh1.scproxy.top
    path: /shirker
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 9
  password: EXN3S3eQpjE7EJu8
  port: '9027'
  server: 185.167.116.38
  type: ss
- alterId: '0'
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯
  network: http
  port: '52757'
  server: 8.218.145.251
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: 451d0d8d-6e0b-403c-9fab-937a92f211e2
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 10
  password: M3t2ZEQcMGRWBjRa
  port: '9011'
  server: 185.167.116.38
  type: ss
- alterId: '1'
  cipher: auto
  name: ğŸ‡­ğŸ‡° _CN_ä¸­å›½->ğŸ‡­ğŸ‡°_HK_é¦™æ¸¯
  port: '10001'
  server: 112.33.32.136
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: cb7001c7-e495-41ac-b942-f25f60523414
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 11
  password: VP8ZPxQpJtZRCjfZ
  port: '9080'
  server: 185.167.116.253
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 4
  password: amazonskr05
  port: '443'
  server: 43.201.86.41
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§
  network: ws
  port: '443'
  server: 23.227.38.25
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7
  ws-opts:
    headers:
      Host: oplg1.cfcdn2.xyz
    path: /AUIKN8AU
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 12
  password: wjTugX3ZtHMB9c3Z
  port: '9057'
  server: 185.167.116.253
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 13
  password: HSZuyJQcWe8dxNdF
  port: '9043'
  server: 185.167.116.253
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 9
  password: amazonskr05
  port: '443'
  server: 54.186.216.67
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ _CN_ä¸­å›½->ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
  network: ws
  port: '38301'
  server: in-jp-1.iivvppnn.info
  skip-cert-verify: 'false'
  tls: 'false'
  type: vmess
  uuid: 79386685-16da-327c-9e14-aa6d702d86bc
  ws-opts:
    headers:
      Host: www.ivpnpro.net
    path: /hls/cctv5phd.m3u8
- alterId: '0'
  cipher: auto
  name: _BZ_ä¼¯åˆ©å…¹ 2
  network: ws
  port: '443'
  server: 203.30.191.20
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd
  ws-opts:
    headers:
      Host: clash6.ssr-free.xyz
    path: /dongtaiwang.com
- name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 3
  password: df283334-6f6e-4efb-9a8a-b8ecf3040924
  port: '443'
  server: 150.66.13.75
  skip-cert-verify: 'false'
  sni: tk15.1coinvp.vip
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 10
  password: amazonskr05
  port: '443'
  server: 18.237.102.119
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 14
  password: cp8pRSUAyLhTfVWH
  port: '9064'
  server: 185.167.116.253
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 11
  network: ws
  port: '443'
  server: 172.67.199.31
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c
  ws-opts:
    headers:
      Host: fr1.trump2023.org
    path: /9JZFDTKE
- cipher: aes-256-gcm
  name: ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾ 2
  password: '114514'
  port: '30033'
  server: out.jijifun.com
  type: ss
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 12
  network: ws
  port: '443'
  server: us1.wanwusheng.me
  skip-cert-verify: 'false'
  tls: 'true'
  type: vmess
  uuid: 44ceb389-4cea-4ea1-eef9-11ce6f3effe6
  ws-opts:
    headers:
      Host: us1.wanwusheng.me
    path: /
proxy-groups:
- name: æ‰‹åŠ¨é€‰æ‹©
  proxies:
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 2
  - ğŸ‡­ğŸ‡° _CN_ä¸­å›½->ğŸ‡­ğŸ‡°_HK_é¦™æ¸¯
  - ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 2
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 6
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 9
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡
  - _CN_ä¸­å›½ 2
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 14
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 8
  - ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 3
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 3
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš
  - ğŸ‡¸ğŸ‡¬ _CN_ä¸­å›½->ğŸ‡¸ğŸ‡¬_SG_æ–°åŠ å¡
  - ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾ 2
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 3
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 12
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 7
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 11
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 10
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 13
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 10
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 5
  - ğŸ‡»ğŸ‡³ _VN_è¶Šå—
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 12
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 3
  - ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 3
  - ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§
  - _BZ_ä¼¯åˆ©å…¹ 2
  - ğŸ‡©ğŸ‡ª _DE_å¾·å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 8
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 4
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 11
  - ğŸ‡¯ğŸ‡µ _CN_ä¸­å›½->ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 4
  - _CN_ä¸­å›½
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 4
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 2
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 6
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 9
  - _BZ_ä¼¯åˆ©å…¹
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 7
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 5
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 2
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 2
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬
  type: select
- name: PROXY
  proxies:
  - âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—
  - âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢
  - æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- interval: '300'
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—
  proxies: &id001
  - p0
  - p1
  - p2
  - p3
  - p4
  strategy: consistent-hashing
  type: load-balance
  url: http://www.apple.com/library/test/success.html
- interval: '300'
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-è½®è¯¢
  proxies: *id001
  strategy: round-robin
  type: load-balance
  url: http://www.apple.com/library/test/success.html
- interval: '500'
  name: p0
  proxies:
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 2
  - ğŸ‡­ğŸ‡° _CN_ä¸­å›½->ğŸ‡­ğŸ‡°_HK_é¦™æ¸¯
  - ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 2
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 6
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 9
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡
  - _CN_ä¸­å›½ 2
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 14
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 8
  type: url-test
  url: http://www.apple.com/library/test/success.html
- interval: '500'
  name: p1
  proxies:
  - ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 3
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 3
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš
  - ğŸ‡¸ğŸ‡¬ _CN_ä¸­å›½->ğŸ‡¸ğŸ‡¬_SG_æ–°åŠ å¡
  - ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾ 2
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 3
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 12
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 7
  type: url-test
  url: http://www.apple.com/library/test/success.html
- interval: '500'
  name: p2
  proxies:
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 11
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 10
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 13
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 10
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 5
  - ğŸ‡»ğŸ‡³ _VN_è¶Šå—
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 12
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 3
  - ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 3
  type: url-test
  url: http://www.apple.com/library/test/success.html
- interval: '500'
  name: p3
  proxies:
  - ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§
  - _BZ_ä¼¯åˆ©å…¹ 2
  - ğŸ‡©ğŸ‡ª _DE_å¾·å›½
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 8
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 4
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 11
  - ğŸ‡¯ğŸ‡µ _CN_ä¸­å›½->ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 4
  - _CN_ä¸­å›½
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 4
  type: url-test
  url: http://www.apple.com/library/test/success.html
- interval: '500'
  name: p4
  proxies:
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 2
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 6
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 9
  - _BZ_ä¼¯åˆ©å…¹
  - ğŸ‡¦ğŸ‡º _AU_æ¾³å¤§åˆ©äºš 7
  - ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 5
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½ 2
  - ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 2
  - ğŸ‡°ğŸ‡· _KR_éŸ©å›½
  - ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬
  type: url-test
  url: http://www.apple.com/library/test/success.html
rule-providers:
  apple:
    behavior: domain
    interval: '86400'
    path: ./ruleset/apple.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
  applications:
    behavior: classical
    interval: '86400'
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  cncidr:
    behavior: ipcidr
    interval: '86400'
    path: ./ruleset/cncidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
  direct:
    behavior: domain
    interval: '86400'
    path: ./ruleset/direct.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
  gfw:
    behavior: domain
    interval: '86400'
    path: ./ruleset/gfw.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
  google:
    behavior: domain
    interval: '86400'
    path: ./ruleset/google.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
  greatfire:
    behavior: domain
    interval: '86400'
    path: ./ruleset/greatfire.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
  icloud:
    behavior: domain
    interval: '86400'
    path: ./ruleset/icloud.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
  lancidr:
    behavior: ipcidr
    interval: '86400'
    path: ./ruleset/lancidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
  private:
    behavior: domain
    interval: '86400'
    path: ./ruleset/private.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
  proxy:
    behavior: domain
    interval: '86400'
    path: ./ruleset/proxy.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
  reject:
    behavior: domain
    interval: '86400'
    path: ./ruleset/reject.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
  telegramcidr:
    behavior: ipcidr
    interval: '86400'
    path: ./ruleset/telegramcidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
  tld-not-cn:
    behavior: domain
    interval: '86400'
    path: ./ruleset/tld-not-cn.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
rules:
- RULE-SET,applications,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,reject,REJECT
- RULE-SET,tld-not-cn,PROXY
- RULE-SET,gfw,PROXY
- RULE-SET,greatfire,PROXY
- RULE-SET,telegramcidr,PROXY
- DOMAIN-SUFFIX,bilibili.com,PROXY
- MATCH,DIRECT
socks-port: '7891'
