proxies:
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡ª _DE_å¾·å›½
  network: ws
  port: 80
  server: 89.163.213.20
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 5668ff97-631f-4602-a13f-b56552c67abe
  ws-opts:
    headers:
      Host: 89.163.213.20
    path: /vmess
- alterId: 0
  cipher: auto
  name: ğŸ‡«ğŸ‡· _FR_æ³•å›½
  network: ws
  port: 443
  server: 141.145.193.48
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡¨ğŸ‡¾ _CY_å¡æµ¦è·¯æ–¯->ğŸ‡«ğŸ‡·_FR_æ³•å›½
  network: ws
  port: 443
  server: 203.24.108.10
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 17b2a313-37a0-4945-a8e4-e63375506b4a
  ws-opts:
    headers:
      Host: lg10.cfcdn1.xyz
    path: /A2DJOPFT
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾
  password: e1af570e-b7e2-402d-a60e-a363ffdfee7e
  port: 14109
  server: cdn.alibaba-kunlun.com
  type: ss
- name: ğŸ‡«ğŸ‡· _FR_æ³•å›½ 2
  password: af6a3685-c423-4579-bfea-784c453d5e23
  port: 443
  server: t5.teslacdn2.live
  skip-cert-verify: false
  sni: t5.teslacdn2.live
  type: trojan
- name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬
  password: a4b8293b-af60-4f1b-8572-dea4f5b6cdef
  port: 443
  server: 139.162.113.113
  skip-cert-verify: false
  type: trojan
- alterId: 0
  cipher: auto
  name: _BZ_ä¼¯åˆ©å…¹
  network: ws
  port: 443
  server: 203.30.191.19
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd
  ws-opts:
    headers:
      Host: clash6.ssr-free.xyz
    path: /dongtaiwang.com
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _BZ_ä¼¯åˆ©å…¹->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  network: ws
  port: 443
  server: 203.30.191.9
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7
  ws-opts:
    headers:
      Host: oplg1.cfcdn2.xyz
    path: /AUIKN8AU
- alterId: 0
  cipher: auto
  name: ğŸ‡®ğŸ‡³ _IN_å°åº¦
  network: ws
  port: 443
  server: yda6.6bbt.tk
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    headers:
      Host: yda6.6bbt.tk
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½
  network: ws
  port: 443
  server: 172.67.199.34
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 20e92881-5fb4-4b05-bc77-57929476dc69
  ws-opts:
    headers:
      Host: lu.sharecentre.online
    path: /shirker
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 2
  network: ws
  port: 443
  server: zfc.windowsupdate1.com
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 769c2da7-add3-42e8-a03c-07be9fcf483c
  ws-opts:
    headers:
      Host: us2.yfjc.sbs
    path: /yfjc/us2?ed=2048
- cipher: aes-256-cfb
  name: ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡
  obfs: plain
  obfs-param: ''
  password: vyunme
  port: 443
  protocol: auth_aes128_sha1
  protocol-param: ''
  server: 13.215.27.80
  type: ssr
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾ 2
  password: e1af570e-b7e2-402d-a60e-a363ffdfee7e
  port: 14108
  server: cdn.alibaba-kunlun.com
  type: ss
- name: ğŸ‡¯ğŸ‡µ _CN_ä¸­å›½->ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
  password: 0f098bb2-9fad-3cc3-8acf-2a3268c1eb27
  port: 18433
  server: hn.xiaohouzi.club
  skip-cert-verify: false
  sni: hn.xiaohouzi.club
  type: trojan
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯
  network: http
  port: 61725
  server: 8.218.94.239
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b7eef349-730f-4b56-b0e6-8e58e3e968c3
- alterId: 0
  cipher: auto
  name: ğŸ‡®ğŸ‡³ _IN_å°åº¦ 2
  network: ws
  port: 80
  server: in1.microsoftjs.top
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: bfd69e87-386d-4206-903e-9c0df8a8bfcf
  ws-opts:
    headers:
      Host: in1.microsoftjs.top
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡³ğŸ‡± _NL_è·å…°
  network: ws
  port: 443
  server: hla1.6bbt.tk
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    headers:
      Host: hla1.6bbt.tk
    path: /
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: _LA_è€æŒ
  network: http
  port: 53321
  server: 8.218.83.226
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 7c9df904-38c1-403f-854a-53713f9be045
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 3
  network: ws
  port: 8880
  server: cf-lt.sharecentre.online
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: e59bd762-dacd-445c-8e2a-e1c5812949cb
  ws-opts:
    headers:
      Host: ssrsub.v10.asuka.buzz
    path: /api/v3/download.getFile
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ _CN_ä¸­å›½->ğŸ‡¹ğŸ‡¼_TW_å°æ¹¾ 3
  password: e1af570e-b7e2-402d-a60e-a363ffdfee7e
  port: 14107
  server: cdn.alibaba-kunlun.com
  type: ss
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯ 2
  network: http
  port: 38369
  server: 8.218.36.140
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: c78723e2-7fd2-4621-95a2-fe525855440a
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 4
  network: ws
  port: 443
  server: 170.187.206.48
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 927094d3-d678-4763-8591-e240d0bcae87
  ws-opts:
    path: /
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 5
  password: amazonskr05
  port: 443
  server: 54.203.94.5
  type: ss
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 6
  network: ws
  port: 80
  server: 107.182.28.230
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: dd776000-ed52-4ce9-f88c-c07d9047e687
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 7
  network: ws
  port: 443
  server: 172.64.152.150
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd
  ws-opts:
    headers:
      Host: clash6.ssr-free.xyz
    path: /dongtaiwang.com
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 8
  network: ws
  port: 443
  server: 172.67.45.144
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7
  ws-opts:
    headers:
      Host: oplg1.cfcdn2.xyz
    path: /AUIKN8AU
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 9
  network: ws
  port: 443
  server: germany2.yj2022.ga
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 4b5e4565-322f-4223-a891-78a84f189726
  ws-opts:
    headers:
      Host: germany2.yj2022.ga
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡¸ğŸ‡¬ _SG_æ–°åŠ å¡ 2
  network: ws
  port: 443
  server: sg8.microsoftjs.top
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: bfd69e87-386d-4206-903e-9c0df8a8bfcf
  ws-opts:
    headers:
      Host: sg8.microsoftjs.top
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 2
  network: ws
  port: 443
  server: jp3.microsoftjs.top
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: bfd69e87-386d-4206-903e-9c0df8a8bfcf
  ws-opts:
    headers:
      Host: jp3.microsoftjs.top
    path: /
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯ 3
  network: http
  port: 36595
  server: 8.218.79.195
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: e8781ba1-7c16-46a3-a24a-ebb52e83f006
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 10
  password: amazonskr05
  port: 443
  server: 35.92.132.241
  type: ss
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 11
  network: ws
  port: 443
  server: mga9.6bbt.tk
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    headers:
      Host: mga9.6bbt.tk
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡³ğŸ‡± _NL_è·å…° 2
  network: ws
  port: 443
  server: hla6.6bbt.tk
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    headers:
      Host: hla6.6bbt.tk
    path: /
- name: ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  password: 0f098bb2-9fad-3cc3-8acf-2a3268c1eb27
  port: 17106
  server: hnm.xiaohouzi.club
  skip-cert-verify: false
  sni: hnm.xiaohouzi.club
  type: trojan
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯ 4
  network: http
  port: 31705
  server: 47.243.111.25
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: d0fc2199-6bb4-4559-a7ec-48f3d728500d
- cipher: aes-256-cfb
  name: ğŸ‡®ğŸ‡ª _IE_çˆ±å°”å…°
  obfs: http_simple
  obfs-param: www.microsoft.com#User-Agent:Mozilla/5.0(iPhone;CPUiPhoneOS11_4_1likeMacOSX)AppleWebKit/602.4.6(KHTML,likeGecko)Version/10.0Mobile/14D27MicroMessenger/6.5.13Accept:/Connection:keep-alive
  password: YpX2opBbrfqJzzMs
  port: 42833
  protocol: origin
  protocol-param: ''
  server: z0116.security-cloudfront-cdn.com
  type: ssr
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½ 2
  password: e1af570e-b7e2-402d-a60e-a363ffdfee7e
  port: 14112
  server: cdn.alibaba-kunlun.com
  type: ss
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 12
  network: ws
  port: 443
  server: buyvm-ny.sharecentre.online
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 20e92881-5fb4-4b05-bc77-57929476dc69
  ws-opts:
    headers:
      Host: buyvm-ny.sharecentre.online
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ _JP_æ—¥æœ¬ 3
  network: ws
  port: 443
  server: vjp2.0bad.com
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 927094d3-d678-4763-8591-e240d0bcae87
  ws-opts:
    headers:
      Host: vjp2.0bad.com
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 13
  network: ws
  port: 443
  server: buyvm.sharecentre.online
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 20e92881-5fb4-4b05-bc77-57929476dc69
  ws-opts:
    headers:
      Host: buyvm.sharecentre.online
    path: /shirker
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½->ğŸ‡«ğŸ‡·_FR_æ³•å›½
  network: ws
  port: 443
  server: 141.193.213.21
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c
  ws-opts:
    headers:
      Host: fr1.trump2023.org
    path: /9JZFDTKE
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 14
  network: ws
  port: 80
  server: 172.67.199.34
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8b6dd709-4d4e-4b92-f542-54a676efbfe4
  ws-opts:
    headers:
      Host: la.awsbest.com
    path: /shares
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 15
  network: ws
  port: 443
  server: lu.sharecentre.online
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 20e92881-5fb4-4b05-bc77-57929476dc69
  ws-opts:
    headers:
      Host: lu.sharecentre.online
    path: /shirker
- alterId: 0
  cipher: auto
  name: ğŸ‡«ğŸ‡· _FR_æ³•å›½ 3
  network: ws
  port: 443
  server: 141.145.193.76
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 6e41c22a-2794-4504-a05a-4f8def6d0bf5
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸ _CN_ä¸­å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½ 3
  password: 0f098bb2-9fad-3cc3-8acf-2a3268c1eb27
  port: 20039
  server: iplc.xiaohouzi.club
  skip-cert-verify: false
  sni: $azhk02.xiaohouzi.club
  type: trojan
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½ 16
  network: ws
  port: 443
  server: us-dp.sharecentre.online
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 20e92881-5fb4-4b05-bc77-57929476dc69
  ws-opts:
    headers:
      Host: us-dp.sharecentre.online
    path: /
- name: ğŸ‡®ğŸ‡© _ID_å°åº¦å°¼è¥¿äºš
  password: cf2af470-b8f1-11ed-b133-205c6d5f5d78
  port: 443
  server: asia1.oceis.net
  skip-cert-verify: false
  sni: mobilelegends.com
  type: trojan
- alterId: 0
  cipher: auto
  name: ğŸ‡­ğŸ‡° _CN_ä¸­å›½->ğŸ‡­ğŸ‡°_HK_é¦™æ¸¯
  port: 10001
  server: 36.156.102.166
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: cb7001c7-e495-41ac-b942-f25f60523414
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ _US_ç¾å›½->ğŸ‡©ğŸ‡ª_DE_å¾·å›½
  network: ws
  port: 443
  server: finland2.yj2022.ga
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 4b5e4565-322f-4223-a891-78a84f189726
  ws-opts:
    headers:
      Host: finland2.yj2022.ga
    path: /
- name: ğŸ‡­ğŸ‡° _HK_é¦™æ¸¯ 5
  password: 8165e695-0746-4d45-ad56-24431b21f546
  port: 443
  server: dl-hk5.steamdownload.top
  skip-cert-verify: false
  sni: data-hk.xn--vur082k.cc
  type: trojan
